SELECT elections.state,
		elections.year,
		elections.cd AS cd1,
		elections.cd2,
		elections.cd3,
		elections.cd4,
		elections.cd5,
		elections.g_USP_dv,
		elections.g_USP_rv,
		elections.g_USH_dv AS g_USH_dv1,
		elections.g_USH_rv AS g_USH_rv1,
		elections.g_USH_dv2,
		elections.g_USH_rv2,
		elections.g_USH_dv3,
		elections.g_USH_rv3,
		elections.g_USH_dv4,
		elections.g_USH_rv4,
		elections.g_USH_dv5,
		elections.g_USH_rv5,
		elections.g_USH_d2v,
		elections.g_USH_r2v,
		elections.g_USH_r3v
	FROM dissertData..elections

SELECT elections.state,
		elections.year,
		elections.g_GOV_dv AS gov_dem,
		elections.g_GOV_rv AS gov_rep,
 		elections.g_USS_dv AS uss_dem,
		elections.g_USS_rv AS uss_rep,
		elections.g_USP_dv AS usp_dem,
		elections.g_USP_rv AS usp_rep,
		elections.g_LTG_dv AS ltg_dem,
		elections.g_LTG_rv AS ltg_rep,
		elections.g_ATG_dv AS atg_dem,
		elections.g_ATG_rv AS atg_rep,
		elections.g_AUD_rv AS aud_rep,
		elections.g_AUD_dv AS aud_dem,
		elections.g_TRE_rv AS tre_rep,
		elections.g_TRE_dv AS tre_dem,
		elections.g_COM_rv AS con_rep,
		elections.g_COM_dv AS con_dem,
		elections.g_INS_rv AS ins_rep,
		elections.g_INS_dv AS ins_dem,
		elections.g_LND_rv AS lnd_rep,
		elections.g_LND_dv AS lnd_dem,
		elections.g_AGR_rv AS agr_rep,
		elections.g_AGR_dv AS agr_dem,
		elections.g_LBR_rv AS lbr_rep,
		elections.g_LBR_dv AS lbr_dem,
		elections.g_SOS_dv AS sos_dem,
		elections.g_SOS_rv AS sos_rep
	FROM dissertData..elections
--Need to figure out how to exclude total precincts, as well as whether abs, EV, etc. lines should be removed.
